### ISSUE TITLE
Large runtime error after succesful chocopy project build

### ISSUE THREAD

**Issue by jonay2000** [metaborg/stratego#20]
**Describe the bug**
I've got some stratego code dealing with hashmaps

![image](https://user-images.githubusercontent.com/22172241/143037832-4781b89d-e433-4831-ad15-712635626648.png)

My stratego project with this code builds. However, when actually compiling some chocopy code to riscv, it looks like chocopy never executes. I have multiple `debug` functions scattered around and none of them print anything. Instead a large error is printed to the console (attached below). Note that there's no eclipse pop-up. It only prints this error to the console.

**Project**
When compiling stratego as a part of spoofax 0.16.11

**Versions**

**To Reproduce**
use the above code somwhere. Here it's in text:

```
	construct-graph: ([], graph) -> graph
	construct-graph: ([instr{Live(live, writes)} | rest], graph) -> updated-graph
		// initialize all live registers and write registers in the hashtable to ensure they exist
		where <map(?i; <hashtable-get(|i)> graph <+ <hashtable-put(|i, [])> graph)> <conc> (live, writes)
		// filter out all written registers from live to get which registers are *actually* in use 
		// this avoids self-edges (page 40 in Essentials of compilation)
		where <filter(where(<not(member)>(<id>, writes)))> live => used_registers
		// construct edges from every used register to all written registers
		where <cart(?(x, y); <graph-append(|x, y)> graph; <graph-append(|y, x)> graph); concat> (writes, used_registers) => edges
		where <construct-graph> (rest, graph) => updated-graph
```

You can also take a look at my gitlab repository (for cs4200 TAs only). There you can build this file to riscv32im
https://gitlab.ewi.tudelft.nl/CS4200/2021-2022/student-jdonszelmann/-/blob/milestone-3-develop/chocopy.backend/example/example.cpyb

**Expected behaviour**
I believe this code should work (and generate a graph for coloring to use in register allocations)

**Additional context**
```
mb.pie.api.ExecException: mb.stratego.common.StrategoExceptions$StrategyFail: Invoking Stratego strategy 'stratego2-compile-top-level-def' failed 
Stratego stack trace:
	dr_scope_1_1
	m_transform_no_overlays_1_0
	frontend_sep_comp_0_0
	stratego2_compile_top_level_def_0_0
	stratego2_compile_top_level_def_0_0
Stratego input term:
Specification(
  [ Signature([Constructors([])])
  , Strategies(
      [ RDefNoArgs(
          "construct-graph"
        , Rule(
            NoAnnoList(Tuple([NoAnnoList(List([])), Var("graph")]))
          , Var("graph")
          , []
          )
        )
      , RDefNoArgs(
          "construct-graph"
        , Rule(
            NoAnnoList(
              Tuple(
                [ NoAnnoList(
                    ListTail(
                      [ AnnoList(
                          Var("instr")
                        , [NoAnnoList(Op("Live", [Var("live"), Var("writes")]))]
                        )
                      ]
                    , Var("rest")
                    )
                  )
                , Var("graph")
                ]
              )
            )
          , Var("updated-graph")
          , [ WhereClause(
                BA(
                  CallT(
                    SVar("map")
                  , [ LChoice(
                        Seq(
                          Match(Var("i"))
                        , BA(
                            CallT(SVar("hashtable-get"), [], [Var("i")])
                          , Var("graph")
                          )
                        )
                      , BA(
                          CallT(
                            SVar("hashtable-put")
                          , []
                          , [Var("i"), NoAnnoList(List([]))]
                          )
                        , Var("graph")
                        )
                      )
                    ]
                  , []
                  )
                , App(
                    CallT(SVar("conc"), [], [])
                  , NoAnnoList(Tuple([Var("live"), Var("writes")]))
                  )
                )
              )
            , WhereClause(
                AM(
                  BA(
                    CallT(
                      SVar("filter")
                    , [ Where(
                          BA(
                            Not(CallT(SVar("member"), [], []))
                          , NoAnnoList(Tuple([RootApp(Id()), Var("writes")]))
                          )
                        )
                      ]
                    , []
                    )
                  , Var("live")
                  )
                , Var("used_registers")
                )
              )
            , WhereClause(
                AM(
                  BA(
                    Seq(
                      CallT(
                        SVar("cart")
                      , [ Seq(
                            Match(NoAnnoList(Tuple([Var("x"), Var("y")])))
                          , Seq(
                              BA(
                                CallT(
                                  SVar("graph-append")
                                , []
                                , [Var("x"), Var("y")]
                                )
                              , Var("graph")
                              )
                            , BA(
                                CallT(
                                  SVar("graph-append")
                                , []
                                , [Var("y"), Var("x")]
                                )
                              , Var("graph")
                              )
                            )
                          )
                        ]
                      , []
                      )
                    , CallT(SVar("concat"), [], [])
                    )
                  , NoAnnoList(Tuple([Var("writes"), Var("used_registers")]))
                  )
                , Var("edges")
                )
              )
            , WhereClause(
                AM(
                  BA(
                    CallT(SVar("construct-graph"), [], [])
                  , NoAnnoList(Tuple([Var("rest"), Var("graph")]))
                  )
                , Var("updated-graph")
                )
              )
            ]
          )
        )
      ]
    )
  ]
)
	at mb.str.incr.Spoofax3StrategoLanguage.callStrategy(Spoofax3StrategoLanguage.java:148)
	at mb.str.incr.Spoofax3StrategoLanguage.desugar(Spoofax3StrategoLanguage.java:108)
	at mb.stratego.build.strincr.task.input.BackInput$Normal.buildCTree(BackInput.java:256)
	at mb.stratego.build.strincr.task.Back.exec(Back.java:106)
	at mb.stratego.build.strincr.task.Back.exec(Back.java:74)
	at mb.pie.api.Task.exec(Task.java:56)
	at mb.pie.runtime.exec.TaskExecutor.execInternal(TaskExecutor.java:130)
	at mb.pie.runtime.exec.TaskExecutor.exec(TaskExecutor.java:87)
	at mb.pie.runtime.exec.BottomUpRunner.exec(BottomUpRunner.java:370)
	at mb.pie.runtime.exec.BottomUpRunner.execAndSchedule(BottomUpRunner.java:133)
	at mb.pie.runtime.exec.BottomUpRunner.execScheduled(BottomUpRunner.java:120)
	at mb.pie.runtime.exec.BottomUpRunner.requireInitial(BottomUpRunner.java:83)
	at mb.pie.runtime.MixedSessionImpl.lambda$updateAffectedBy$0(MixedSessionImpl.java:72)
	at mb.pie.runtime.SessionImpl.handleException(SessionImpl.java:227)
	at mb.pie.runtime.MixedSessionImpl.updateAffectedBy(MixedSessionImpl.java:72)
	at mb.spoofax.lwb.eclipse.SpoofaxLwbBuilder.bottomUpBuild(SpoofaxLwbBuilder.java:197)
	at mb.spoofax.lwb.eclipse.SpoofaxLwbBuilder.incrBuild(SpoofaxLwbBuilder.java:144)
	at mb.spoofax.lwb.eclipse.SpoofaxLwbBuilder.access$100(SpoofaxLwbBuilder.java:61)
	at mb.spoofax.lwb.eclipse.SpoofaxLwbBuilder$1.run(SpoofaxLwbBuilder.java:92)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at mb.spoofax.lwb.eclipse.SpoofaxLwbBuilder.build(SpoofaxLwbBuilder.java:101)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:846)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:229)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:277)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:330)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:333)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:385)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:406)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:515)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:412)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: mb.stratego.common.StrategoExceptions$StrategyFail: Invoking Stratego strategy 'stratego2-compile-top-level-def' failed 
Stratego stack trace:
	dr_scope_1_1
	m_transform_no_overlays_1_0
	frontend_sep_comp_0_0
	stratego2_compile_top_level_def_0_0
	stratego2_compile_top_level_def_0_0
Stratego input term:
Specification(
  [ Signature([Constructors([])])
  , Strategies(
      [ RDefNoArgs(
          "construct-graph"
        , Rule(
            NoAnnoList(Tuple([NoAnnoList(List([])), Var("graph")]))
          , Var("graph")
          , []
          )
        )
      , RDefNoArgs(
          "construct-graph"
        , Rule(
            NoAnnoList(
              Tuple(
                [ NoAnnoList(
                    ListTail(
                      [ AnnoList(
                          Var("instr")
                        , [NoAnnoList(Op("Live", [Var("live"), Var("writes")]))]
                        )
                      ]
                    , Var("rest")
                    )
                  )
                , Var("graph")
                ]
              )
            )
          , Var("updated-graph")
          , [ WhereClause(
                BA(
                  CallT(
                    SVar("map")
                  , [ LChoice(
                        Seq(
                          Match(Var("i"))
                        , BA(
                            CallT(SVar("hashtable-get"), [], [Var("i")])
                          , Var("graph")
                          )
                        )
                      , BA(
                          CallT(
                            SVar("hashtable-put")
                          , []
                          , [Var("i"), NoAnnoList(List([]))]
                          )
                        , Var("graph")
                        )
                      )
                    ]
                  , []
                  )
                , App(
                    CallT(SVar("conc"), [], [])
                  , NoAnnoList(Tuple([Var("live"), Var("writes")]))
                  )
                )
              )
            , WhereClause(
                AM(
                  BA(
                    CallT(
                      SVar("filter")
                    , [ Where(
                          BA(
                            Not(CallT(SVar("member"), [], []))
                          , NoAnnoList(Tuple([RootApp(Id()), Var("writes")]))
                          )
                        )
                      ]
                    , []
                    )
                  , Var("live")
                  )
                , Var("used_registers")
                )
              )
            , WhereClause(
                AM(
                  BA(
                    Seq(
                      CallT(
                        SVar("cart")
                      , [ Seq(
                            Match(NoAnnoList(Tuple([Var("x"), Var("y")])))
                          , Seq(
                              BA(
                                CallT(
                                  SVar("graph-append")
                                , []
                                , [Var("x"), Var("y")]
                                )
                              , Var("graph")
                              )
                            , BA(
                                CallT(
                                  SVar("graph-append")
                                , []
                                , [Var("y"), Var("x")]
                                )
                              , Var("graph")
                              )
                            )
                          )
                        ]
                      , []
                      )
                    , CallT(SVar("concat"), [], [])
                    )
                  , NoAnnoList(Tuple([Var("writes"), Var("used_registers")]))
                  )
                , Var("edges")
                )
              )
            , WhereClause(
                AM(
                  BA(
                    CallT(SVar("construct-graph"), [], [])
                  , NoAnnoList(Tuple([Var("rest"), Var("graph")]))
                  )
                , Var("updated-graph")
                )
              )
            ]
          )
        )
      ]
    )
  ]
)
14:53:05.375 | TRACE | Worker-263: To RV32IM file                         | mb.spoofax.eclipse.command.RunCommandJob           | Running command job for 'To RV32IM file' from language 'chocopy.backend'
14:53:05.375 | TRACE | Worker-263: To RV32IM file                         | mb.spoofax.eclipse.pie.PieRunner                   | Require (without observing) 'mb.chocopy.show.ShowCompileToRv32ImFile(ShowCompileToRv32ImFile$Args{rootDirectory=eclipse-resource##/chocopy.backend, file=eclipse-resourc...)'
14:53:05.375 | DEBUG | Worker-263: To RV32IM file                         | mb.pie.runtime.tracer.LoggingTracer                | → mb.chocopy.show.ShowCompileToRv32ImFile(ShowCompileToRv32ImFile$Args{rootDirectory=eclipse-resource##/chocopy.backend, file=eclipse-resource##/chocopy.backend/example/example.cpyb}) (reason: inconsistent provided resource eclipse-resource##/chocopy.backend/example/example.cpyb.rv32im)
14:53:05.553 | DEBUG | Worker-263: To RV32IM file                         | mb.pie.runtime.tracer.LoggingTracer                | ← CommandFeedback{messages=KeyedMessages(0 messages), exception=null, showFeedbacks=[show file 'eclipse-resource##/chocopy.backend/example/example.cpyb.rv32im']}
14:53:05.891 | TRACE | Worker-267: rv32im editor update                   | mb.spoofax.eclipse.editor.EditorUpdateJob          | Running rv32im editor update job for L/chocopy.backend/example/example.cpyb.rv32im
14:53:05.891 | TRACE | Worker-267: rv32im editor update                   | mb.spoofax.eclipse.pie.PieRunner                   | Adding or updating editor for 'L/chocopy.backend/example/example.cpyb.rv32im'
14:53:05.891 | TRACE | Worker-267: rv32im editor update                   | mb.spoofax.eclipse.pie.PieRunner                   | Update affected by 1 resources with tags '[Interactive]'
```

**Comment by jonay2000** [comment]
I figured out that it could be a mistake in my code. I still think the error is cryptic but It could have to do with this line:
```
where <map(?i; <hashtable-get(|i)> graph <+ <hashtable-put(|i, [])> graph)> <conc> (live, writes)
```

I want it to 
1. match i
2. do a hashmap lookup
3. if that fails insert

I'm not entirely sure what the associativity is of <+ and if whether or not it always does the ?i match.

**Comment by jonay2000** [comment]
note that the offending code is here: https://gitlab.ewi.tudelft.nl/CS4200/2021-2022/student-jdonszelmann/-/blob/milestone-3-develop/chocopy.backend/src/register_allocation.str2

I believe this part is the issue as before I added it everything worked.

**Comment by Apanatshka** [comment]
I think you've found an edge case where the new Stratego 2 compiler frontend and some old tests in the backend have conflicting ideas of what constitutes an unbound variable. Truly unbound variable are not allowed to be built, but possibly unbound variables are considered ok (and will give a `fail` at runtime is truly unbound). 

Your argument to the map strategy: `?i; <hashtable-get(|i)> graph <+ <hashtable-put(|i, [])> graph)`, is parsed as `(?i; <hashtable-get(|i)> graph) <+ <hashtable-put(|i, [])> graph)`. According to an internal check, this means that `i` is unbound when used as an argument to `hashtable-put`. According to the new Stratego 2 frontend, `i` might be bound at that point because `map` can call the strategy multiple times. So you can work around this issue by using this as the argument to map: `?i; (<hashtable-get(|i)> graph <+ <hashtable-put(|i, [])> graph))`. I'll fix the problem in the next release.
